# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/smart_tasks_design',
                'doc_host': 'https://hgzech.github.io',
                'git_url': 'https://github.com/hgzech/smart_tasks_design',
                'lib_path': 'smart_tasks_design'},
  'syms': { 'smart_tasks_design.core': { 'smart_tasks_design.core.say_hello': ( 'smart_tasks_design.html#say_hello',
                                                                                'smart_tasks_design/core.py')}}}