# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_smart_tasks_design.ipynb.

# %% auto 0
__all__ = ['say_hello']

# %% ../00_smart_tasks_design.ipynb 4
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'
